################################################################################
# Minima MySQL MEG..                                                           #
#                                                                              #
# Full Minima node backed by a MySQL database with MEG..                       #
################################################################################

version: "3"
services:
  #MySQL Database to store all Minima Data.. all TxPoW etc..
  mysql:
    image: mysql:8.4
    environment:
      #You can change the root password
      MYSQL_ROOT_PASSWORD: "RRiCYfhmd03dx0IuHBxaKynI66PUt90SMvEK"
      #You can leave these.. ONLY change these if you ALSO change the login details below
      MYSQL_USER: "minimauser"
      MYSQL_PASSWORD: "iJwxexR4v3x52Ult5xJi8uAXnqNVhhZo7wpX"
      MYSQL_DATABASE: "minimadb"
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql
    #You can access the MySQL db if you want by opening the port
    ports:
      - 127.0.0.1:3310:3306
    networks:
      my-shared-network:
        aliases:
          - meganode-mysql

  #Minima Node
  minima:
    image: minimaglobal/minima:dev
    stop_grace_period: 60s
    restart: unless-stopped
    environment:
      #Main MDS password
      #minima_mdspassword: "123"

      #Initial PEERS - you can edit this or use the default
      minima_p2pnodes: "https://spartacusrex.com/minimapeers.txt"

      #If you are running on Desktop / no external IP enable this setting
      #minima_desktop: true
      #You must have rpc enabled so MEG can communicate - do NOT open port 9005
      minima_rpcenable: "true"
      #Enable the Public MDS
      #minima_publicmds: "true"
      minima_mdsenable: "false"
      #I use solo to test / debug
      #minima_solo: "true"
      #MDS is ENABLED by default in the container so you MUST set your MDS password to something good..
      minima_megammr: "true"
      minima_megaprune: "true"
      #MySQL login profiles:
      minima_mysqldb: "minimauser:iJwxexR4v3x52Ult5xJi8uAXnqNVhhZo7wpX@meganode-mysql:3306/minimadb"
      minima_mysqldbdelay: "10000"
      minima_mysqlalltxpow: "true"
      minima_mysqldbcoins: "true"
      minima_rpccrlf: "true"
    #Opening the Minima ports.. You can change these if you are running multiple version on the same host
    ports:
      #Main Minima port - you can remove this if you don't have an external IP
      - 127.0.0.1:9001:9001
      #MDS port..
      - 127.0.0.1:9003:9003
      - 127.0.0.1:9005:9005
    #The main Minima data folder where you can load mysql archive files
    volumes:
      - ./data:/home/minima/data
      - ./backups:/home/minima/backups
    depends_on:
      - mysql
    networks:
      - my-shared-network

  #The MEG node.. waits for Minima to start
  # meg:
  #   image: minimaglobal/meg:dev
  #   stop_grace_period: 60s
  #   restart: unless-stopped
  #   ports:
  #     - 127.0.0.1:8080:8080
  #   environment:
  #     #The MAIN admin password - CHANGE this
  #     meg_adminpassword: "mypassword"

  #     #Do NOT change these..
  #     meg_minimarpc: "http://minima:9005/"
  #     meg_meghost: "http://meg:8080"

  #     #NEED this as minima waits for mysql
  #     meg_startupdelay: "20000"
  #   depends_on:
  #     - minima
  #   networks:
  #     - my-shared-network

  # #The CRON job that runs a backup of MEG and Mysql every 24 hours..
  # cron:
  #   build:
  #     context: .
  #     dockerfile: CRON.Dockerfile
  #   entrypoint: ["bash", "-c", "cron -f"]
  #   restart: unless-stopped
  #   depends_on:
  #     - minima

networks:
  my-shared-network:
    external: true
